### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by Kaif-Kutchwala** [AustL/PygameWidgets#20]
Dropdowns would be a great widget to add. Some things to perhaps keep in mind:
- Setting a minimum size or number of options visible
- Scrolling, if there are more options than the specified range
- Formatting the text (left/right justified, centered)
- Direction of the dropdown: U/down/left/right

**Comment by slashformotion** [comment]
I'm gonna try to do this. @AustL

**Comment by slashformotion** [comment]
![TEST_dropdown](https://user-images.githubusercontent.com/45801817/120114649-6a665c80-c180-11eb-96ae-5c6347653aef.gif)

I have this ... It's not great, there is no direction for the moment...

The branch is here =>https://github.com/slashformotion/PygameWidgets/tree/dropdown

**Comment by AustL** [comment]
Looking great so far.

**Comment by slashformotion** [comment]
This is fixed in PR #24
