### ISSUE TITLE
Possible bugs in TextBox widget, regarding font and input text

### ISSUE THREAD

**Issue by bowpie** [AustL/PygameWidgets#21]
Hi! I have encountered two possible bugs/issues when using the textbox widget:

####  1. Custom font TypeError:

When I pass a custom font as an argument to the __init__() method of textbox, I get a TypeError:
` 'pygame.font.Font' object is not iterable.`  I’ve looked at `self.font` inside the class and I’ve changed it from : 
`self.font = pygame.font.SysFont(kwargs.get('font', 'sans-serif'), self.fontSize) `
to:  
`self.font = kwargs.get('font', pygame.font.SysFont('sans-serif', self.fontSize))`, and it worked great.

#### 2. IndexError when the cursor is at the end of the input text:

When the blinking cursor is at the end of the text, before submitting it to getText() method, after I press enter, I get an IndexError in self.draw() : 

```
(x[self.cursorPosition], self._y + self.cursorOffsetTop),
IndexError: list index out of range
```

I’ve managed to fix this one too, using a basic try and except, in self.draw(): 

```
if self.showCursor:
                try:
                    pygame.draw.line(
                        self.win, (0, 0, 0),
                        (x[self.cursorPosition], self._y + self.cursorOffsetTop),
                        (x[self.cursorPosition], self._y + self._height - self.cursorOffsetTop)
                    )
                except IndexError:
                    self.cursorPosition -= 1
```

This only works when the cursor is at the end of the given input, but I have experienced similar problems when it’s at the beginning of the text, or `when passing in an empty string : ‘ ‘ to self.setText()`. 

You should be able to fix those issues without much of a problem.

**Comment by AustL** [comment]
I have made the fixes specified here. However, I cannot replicate the IndexError in the 2nd issue. Could you please describe how to replicate the error?

**Comment by bowpie** [comment]
Right now, it seems I can't replicate the IndexError when submitting the text. However, `setText("")` method still causes an IndexError. I think this and the one I had before are similar. Both errors are happening due to improper handling of array's indexes. Here's the code if you want to replicate that issue:


```
import pygame
from pygame_widgets import *

pygame.init()

screen = pygame.display.set_mode([1000, 800])

running = True

def onsubmit_callback():
    global box
    box.setText("")

box = TextBox(screen, 100, 100, 130, 80, fontSize=50,colour=(80,80,0),
            borderColour=(0, 255, 0), textColour=(0, 255, 0), radius=10, 
            borderThickness=5, onSubmit=onsubmit_callback, textVAlign='centre')


while running:

    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            running = False


    screen.fill((100, 100, 100))
    box.draw()
    box.listen(events)
    pygame.display.update()


pygame.quit()


```

**Comment by AustL** [comment]
It seems that this is due to not updating the cursor position when setting the text. Is fixed now.
