### ISSUE TITLE
Documentation refactoring

### ISSUE THREAD

**Issue by slashformotion** [AustL/PygameWidgets#25]
The documentation is becoming difficult to navigate. 

Perhaps it's time to put a navigation system in place to help people finding what they need

I can do it if you need

**Comment by AustL** [comment]
I've added basic anchors to the Readme, but as the project gets more complex, multi-paged documentation like readthedocs.io might become useful.

**Comment by slashformotion** [comment]
I have used read the doc in the [past](https://secondorderelec.readthedocs.io/en/latest/module.html#secondorderelec). It is best to use it when the docstrings are in place. Here it's not the case. 

perhaps it's best to create a folder named docs and separate the documentation into separate files.

**Comment by AustL** [comment]
Done.

**Comment by slashformotion** [comment]
@AustL I'm learning to create some jekyll websites. Since your documentation is writen in markdown it will be pretty easy to implement. (perhaps even easier than rdt).

Check this theme out : https://jekyll-themes.com/docsy-jekyll/

**Comment by AustL** [comment]
I haven't used jekyll websites before but it looks good.

**Comment by slashformotion** [comment]
I tried to get a sphinx documentation working. You can host it for free on https://readthedocs.org.

The branch is here: https://github.com/slashformotion/PygameWidgets/tree/docs

The result look like this :
![](https://i.imgur.com/7fjCfgM.png)

**Comment by slashformotion** [comment]
There is still a lot of work to do. I am wondering if this is the best solution for this project

I used sphinx on a module developped for school: https://github.com/slashformotion/SecondOrderElec .
