### ISSUE TITLE
Add border feature to Buttons

### ISSUE THREAD

**Issue by Patch4747** [AustL/PygameWidgets#30]
Being able to have a border for a `Button` would be a great addition. Some parameters I had in mind:

- `borderThickness` (defaults to `0`)
- `borderColour` (defaults to `(0,0,0)` maybe)

You might need to add pressed and hover colors, too; I'm not sure.

**Comment by AustL** [comment]
This shouldn't be too difficult (borders are already implemented on textbox for example). Will do this soon.
