### ISSUE TITLE
pygame.draw.rect error

### ISSUE THREAD

**Issue by doojinkang** [AustL/PygameWidgets#4]
Test under python 3.7.6 pygame 1.9.6

File ".../pygame_widgets/button.py", line 124, in draw
border_radius=self.radius
TypeError: rect() takes no keyword arguments

Please see
https://github.com/AustL/PygameWidgets/commit/0b7741e789fa44f2f6acd2d6578a536dfef93bc1

**Comment by AustL** [comment]
This required the pygame version 2.0.0dev to specify a border radius. The dependency has been added.
